### ISSUE TITLE
Build support for Windows

### ISSUE THREAD

**Issue by cosminnicula** [facebook/fixed-data-table#126]
I have Windows 8.1 and Cygwin on my PC.
Inside Cygwin Terminal, I run the following command:
```
./build_helpers/startSiteDevServer.sh
```
However, I get the following error:

```
: invalid optionstartSiteDevServer.sh: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./build_helpers/startSiteDevServer.sh: line 4: $'\r': command not found
: No such file or directoryvServer.sh: line 7: ./build_helpers/buildAPIDocs.sh

module.js:340
    throw err;
          ^
'rror: Cannot find module 'D:\cygdrive\d\X\Offline\Projects\fixed-data-table\site\webpack-prerender.config.js
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (D:\X\Offline\Projects\fixed-data-table\node_modules\webpack\bin\convert-argv.js:56:13)
    at Object.<anonymous> (D:\X\Offline\Projects\fixed-data-table\node_modules\webpack\bin\webpack.js:56:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
: No such file or directoryvServer.sh: line 9: ./build_helpers/buildSiteIndexPages.sh

module.js:340
    throw err;
    ^
Error: Cannot find module 'D:\cygdrive\d\X\Offline\Projects\fixed-data-table\site\webpack-client.config.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (D:\X\Offline\Projects\fixed-data-table\node_modules\webpack\bin\convert-argv.js:56:13)
    at Object.<anonymous> (D:\X\Offline\Projects\fixed-data-table\node_modules\webpack-dev-server\bin\webpack-dev-server.js:46:48)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
I can assure you that webpack-prerender.config.js and webpack-client.config.js are there.

I also tried:
```
npm run site-dev-server
```
...but I get the following error:

```
'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! fixed-data-table@0.1.2 site-dev-server: `./build_helpers/startSiteDevServer.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fixed-data-table@0.1.2 site-dev-server script.
npm ERR! This is most likely a problem with the fixed-data-table package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./build_helpers/startSiteDevServer.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls fixed-data-table
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "site-dev-server"
npm ERR! cwd D:\X\Offline\Projects\fixed-data-table
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm
```
...which btw, seems to be avoided by running directly the .sh script from Cygwin (see above).

Any ideas how to get this working on Windows?

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by fru** [comment]
@pieterv Would you consider a pull request cleaning up the webpack build system for this project? At the same time I could also reduce the reliance on .sh scripts.

**Comment by justinmasse** [comment]
Same issue effecting my workflow.

**Comment by KamranAsif** [comment]
Hey,

We have a forked repo [fixed-data-table-2](https://github.com/schrodinger/fixed-data-table-2) that uses webpack, along with new features, bug fixes, unit testing, etc.
