### ISSUE TITLE
"Error: Cannot read property 'hasOwnProperty' of undefined" when running example.

### ISSUE THREAD

**Issue by f15gdsy** [facebook/fixed-data-table#266]
Hi I tried to run the [example](https://facebook.github.io/fixed-data-table/) in Getting Start section, and get the following error:

> Uncaught (in promise) Error: Cannot read property 'hasOwnProperty' of undefined
	Error loading file:///Users/Yifeng/Desktop/dashboard-editor/app/src/components/app.js
    at Object.checkAndWarnForMutatedProps (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactElementValidator.js:157:27)
    at Object.ReactReconciler.mountComponent (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactReconciler.js:13:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactMultiChild.js:75:46)
    at ReactDOMComponent.Mixin._createContentMarkup (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactDOMComponent.js:146:34)
    at ReactDOMComponent.Mixin.mountComponent (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactDOMComponent.js:95:76)
    at Object.ReactReconciler.mountComponent (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactReconciler.js:11:37)
    at ReactCompositeComponentMixin.mountComponent (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactCompositeComponent.js:99:36)
    at ReactPerf.measure.wrapper [as mountComponent] (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactPerf.js:27:23)
    at Object.ReactReconciler.mountComponent (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactReconciler.js:11:37)
    at ReactCompositeComponentMixin.mountComponent (file:///Users/Yifeng/Desktop/dashboard-editor/jspm_packages/npm/react@0.13.3/lib/ReactCompositeComponent.js:99:36)t @ system.src.js:4181g @ system.src.js:4181(anonymous function) @ system.src.js:4181b @ system.src.js:4181x @ system.src.js:4181p @ system.src.js:4181h @ system.src.js:4181(anonymous function) @ system.src.js:4181

I'm using React@0.13.3, and Fixed-Data-Table@0.4.6, and JSPM.

**Comment by gmeroz** [comment]
I've having the same issue with property 'oneOf'
